#%RAML 1.0
title: Docker API
mediaType: application/json


/v1.24/containers/json?all=1:
  get:
    responses:
      200:
        body:
          application/json:
            example: !include examples/container-list-all.json

/v1.24/containers/json?filters={status=[created]}:
  get:
    responses:
      200:
        body:
          application/json:
            example: !include examples/container-list-filtered-created.json


/v1.24/containers/json?filters={status=[restarting]}:
  get:
    responses:
      200:
        body:
          application/json:
            example: !include examples/container-list-filtered-restarting.json


/v1.24/containers/json?filters={status=[running]}:
  get:
    responses:
      200:
        body:
          application/json:
            example: !include examples/container-list-filtered-running.json

/v1.24/containers/json?filters={status=[paused]}:
  get:
    responses:
      200:
        body:
          application/json:
            example: !include examples/container-list-filtered-paused.json

/v1.24/containers/json?filters={status=[exited]}:
  get:
    responses:
      200:
        body:
          application/json:
            example: !include examples/container-list-filtered-exited.json

/v1.24/containers/json?filters={status=[dead]}:
  get:
    responses:
      200:
        body:
          application/json:
            example: !include examples/container-list-filtered-running.json

/v1.24/containers/running-container/json:
  get:
    responses:
      200:
        body:
          application/json:
            example: !include examples/container-inspect.json

/v1.24/containers/running-container/top:
  get:
    responses:
      200:
        body:
          application/json:
            example: !include examples/container-top.json
