#%RAML 1.0
title: Docker API


/v1.24/containers/json?all=1:
  get:
    responses:
      200:
        body:
          application/json:
            example: !include examples/container-list-all.json

/v1.24/containers/json?filters={"status":["created"]}:
  get:
    responses:
      200:
        body:
          application/json:
            example: !include examples/container-list-filtered-created.json


/v1.24/containers/json?filters={"status":["restarting"]}:
  get:
    responses:
      200:
        body:
          application/json:
            example: !include examples/container-list-filtered-restarting.json


/v1.24/containers/json?filters={"status":["running"]}:
  get:
    responses:
      200:
        body:
          application/json:
            example: !include examples/container-list-filtered-running.json

/v1.24/containers/json?filters={"status":["paused"]}:
  get:
    responses:
      200:
        body:
          application/json:
            example: !include examples/container-list-filtered-paused.json

/v1.24/containers/json?filters={"status":["exited"]}:
  get:
    responses:
      200:
        body:
          application/json:
            example: !include examples/container-list-filtered-exited.json

/v1.24/containers/json?filters={"status":["dead"]}:
  get:
    responses:
      200:
        body:
          application/json:
            example: !include examples/container-list-filtered-dead.json

/v1.24/containers/92c23fc9e379630e6f9a17b19e3da3b/json:
  get:
    responses:
      200:
        body:
          application/json:
            example: !include examples/container-inspect-created-container.json

/v1.24/containers/270f2e51eed51e3c5d5d6b13cdd18d5/json:
  get:
    responses:
      200:
        body:
          application/json:
            example: !include examples/container-inspect-exited-container.json

/v1.24/containers/f911b0f4e0b19e3da3bae6dcff82195/json:
  get:
    responses:
      200:
        body:
          application/json:
            example: !include examples/container-inspect-running-container.json

/v1.24/containers/f911b0f4e0b19e3da3bae6dcff82195/top:
  get:
    responses:
      200:
        body:
          application/json:
            example: !include examples/container-top.json

/v1.24/containers/f911b0f4e0b19e3da3bae6dcff82195/logs?follow=false&stdout=true&stderr=true&timestamps=false&since=0&tail=100:
  get:
    responses:
      200:
        body:
          text/plain:
            example: !include examples/container-logs.txt

/v1.24/containers/f911b0f4e0b19e3da3bae6dcff82195/stats?stream=0:
  get:
    responses:
      200:
        body:
          application/json:
            example: !include examples/container-stats.json