#%RAML 1.0 Library

uses:
  Containers: container-common.raml

types:
  Link: !include ../types/link.raml

  Port:
    properties:
      hostIp: string
      hostPort: string

  Network:
    properties:
      globalIPv6Address: string
      macAddress: string
      aliases?: string
      ipV6Gateway: string
      endpointId: string
      ipPrefixLen: string
      globalIPv6PrefixLen: string
      ipAddress: string
      networkId: string
      gateway: string

  NetworkSettings:
    properties:
      ports?:
        properties:
          .*?: Port
      networks?:
        properties:
          .*?: Network

  Config:
    properties:
      image: string
      hostname: string
      command: string[]
      environment: string[]

  State:
    properties:
      pid: integer
      status: Containers.State
      error: string
      exitCode: integer
      startedTime: string
      finishedTime: string
      dead: boolean
      paused: boolean
      restarting: boolean
      running: boolean

  Details:
    properties:
      id: string
      name: string
      imageId: string
      state: State
      networkSettings: NetworkSettings
      config: Config
      _links:
        properties:
          self: Link
          up: Link
          logs: Link
          top?: Link
          stats: Link
