#%RAML 1.0 Library

types:
  Link: !include ../types/link.raml

  ContainerState:
    enum:
      - created
      - restarting
      - running
      - paused
      - exited
      - dead

  AttachedNetwork:
    properties:
      globalIPv6Address: string
      macAddress: string
      ipv6Gateway: string
      endpointId: string
      ipPrefixLen: number
      globalIPv6PrefixLen: number
      ipAddress: string
      networkId: string
      gateway: string

  Port:
    properties:
      ip: string
      privatePort: number
      publicPort: number
      type: string

  NetworkSettings:
    properties:
      macAddress: string
      ipAddress: string
      ipPrefixLen: number
      bridge: string
      gateway: string
      ports: Port[]
      networks:
        properties:
          //?: AttachedNetwork

  Config:
    properties:
      hostname: string
      attachStdin: boolean
      attachStdout: boolean
      attachStderr: boolean
      tty: boolean
      openStdin: boolean
      stdinOnce: boolean
      command: string
      env: string[]
      workingDir: string

  State:
    properties:
      pid: number
      state: ContainerState
      status: string
      error: string
      exitCode: number
      startedAt: string
      finishedAt: string
      paused: boolean
      restarting: boolean
      running: boolean
      oomKilled: boolean

  Mount:
    properties:
      source: string
      destination: string
      mode: string
      rw: boolean

  Lables:
    properties:
      //?: string

  Container:
    properties:
      id: string
      name: string
      image: string
      imageId: string
      created: number
      networkSettings: NetworkSettings
      config: Config
      state: State
      mounts: Mount[]
      labels: Lables
      _links:
        properties:
          self: Link
          up: Link
          logs: Link
          top?: Link
          stats: Link

  Index:
    properties:
      _embedded:
        type: object
        required: false
        properties:
          containers: Container[]

      stateMetadata:
        type: object
        properties:
          all: number
          created: number
          restarting: number
          running: number
          paused: number
          exited: number
          dead: number

      _links:
        properties:
          all: Link
          created: Link
          restarting: Link
          running: Link
          paused: Link
          exited: Link
          dead: Link
          up: Link
