#%RAML 1.0 Library

uses:
  Containers: container-common.raml

types:
  Link: !include ../types/link.raml

  Port:
    properties:
      ip: string
      privatePort: number
      publicPort: number
      type: string

  Summary:
    properties:
      id: string
      name: string
      image: string
      imageId: string
      status: string
      state: Containers.State
      ports: Port[]
      _links:
        properties:
          self: Link

  Index:
    properties:
      containers: Summary[]
      stateMetadata:
        type: object
        properties:
          all: integer
          created: integer
          restarting: integer
          running: integer
          paused: integer
          exited: integer
          dead: integer
      _links:
        properties:
          self: Link
          up: Link
