#%RAML 1.0
title: Cargo Whale API

uses:
  Containers: libraries/containers.raml
  Authentication: libraries/authentication.raml
  Index: libraries/index.raml

/api:
  get:
    responses:
      200:
        body:
          application/hal+json:
            type: Index.Index
            example: !include examples/index.json
  /authenticate:
    post:
      description: Authenticate with credentials
      body:
        application/json:
          type: Authentication.Credentials
          example: !include examples/credentials.json

  /containers:
    get:
      description: Index for all containers
      queryParameters:
        state:
          type: Containers.ContainerState[]
          description: List of states to filter by
          example: [created, running, dead]
          required: false
      responses:
        200:
          body:
            application/hal+json:
              type: Containers.Index
              examples:
                all: !include examples/container-index.json
                created: !include examples/container-index-created.json
                dead: !include examples/container-index-dead.json
                exited: !include examples/container-index-exited.json
                paused: !include examples/container-index-paused.json
                restarting: !include examples/container-index-restarting.json
                running: !include examples/container-index-running.json
        400:
          body:
            application/hal+json:
              example: !include examples/container-index-400.json
        401:
          body:
            application/json:
              example: !include examples/unauthenticated.json

    /{id}:
      get:
        description: Details about a specific container
        responses:
          200:
            body:
              application/hal+json:
                type: Containers.Container
                example: !include examples/container-details.json
          401:
            body:
              application/json:
                example: !include examples/unauthenticated.json

      /top:
        get:
          description: Processes from a specific container
          responses:
            200:
              body:
                application/hal+json:
                  example: !include examples/container-top.json
            401:
              body:
                application/json:
                  example: !include examples/unauthenticated.json

      /logs:
        get:
          description: Logs from a specific container
          queryParameters:
            details:
              type: boolean
              description: Show extra details provided to logs
              default: false
              required: false
            follow:
              type: boolean
              description: Return a stream
              default: false
              required: false
            stdout:
              type: boolean
              description: Show standard out log
              default: true
              required: false
            stderr:
              type: boolean
              description: Show standard error log
              default: true
              required: false
            timestamps:
              type: boolean
              description: Print timestamps for every log line
              default: true
              required: false
            since:
              type: number
              description: Filter the logs starting at the timestamp
              default: 0
              required: false
            tail:
              type: string
              description: Filters the number of lines returned from the end of the log
              default: "100"
              required: false
          responses:
            200:
              body:
                application/hal+json:
                  example: !include examples/container-logs.json
            401:
              body:
                application/json:
                  example: !include examples/unauthenticated.json

      /stats:
        get:
          description: Processes from a specific container
          responses:
            200:
              body:
                application/hal+json:
                  example: !include examples/container-stats.json
            401:
              body:
                application/json:
                  example: !include examples/unauthenticated.json
